### ISSUE TITLE
pacfinder: error while loading shared libraries: libalpm.so.13

### ISSUE THREAD

**Issue by moritz1000** [stevenbenner/pacfinder#11]
Hello,

since the newest Pacman update PacFinder does not work anymore.

```
❯ pacfinder
pacfinder: error while loading shared libraries: libalpm.so.13: cannot open shared object file: No such file or directory
```
I think it's probably the same problem as described here: https://github.com/Jguer/yay/issues/1604

> Incompatible with pacman 6.0.1-2 (libalpm.so=13)

Kind regards.

**Comment by stevenbenner** [comment]
Thanks for the bug report. I was able to reproduce the issue on my machine.

You should just need to perform a rebuild and reinstall of PacFinder to get it working again.

Re-run the same command(s) that you used to install the package. Please let me know if that remedies the problem, or if it persists.

### Examples

* **yay**

	`yay -S pacfinder`

* **trizen**

	`trizen -S pacfinder`

* **Manual install from AUR**

	```shell
	pacman -S --needed base-devel git
	git clone https://aur.archlinux.org/pacfinder.git
	cd pacfinder
	makepkg -sri
	```

* **Manual install from tarball**

	Follow the instructions in [the project README](https://github.com/stevenbenner/pacfinder?tab=readme-ov-file#install-from-tarball)

### Explanation of error

It looks like libalpm has had a SONAME version bump with the latest pacman release. When you built and installed PacFinder it found and referenced libalpm.so.13. However the latest version of pacman includes libalpm version 14 - so PacFinder will need to be rebuilt to reference libalpm.so.14.

I have quickly looked over [the changes in the latest libalpm](https://gitlab.archlinux.org/pacman/pacman/-/commit/90f5ca42ccf50bc1aa36c8bf9c87610fb731a127) release and I don't think that any of them should cause any problems with PacFinder. The only change that I believe might be relevant is the addition of the new `ALPM_PKG_REASON_UNKNOWN` - but I don't yet know what situation that is used for. I upgraded pacman on my system, and after a rebuild and reinstall of PacFinder, it seems to be working fine.

If you find any problems please open an issue here.

**Comment by moritz1000** [comment]
Thank you so much!
```
❯ yay -S pacfinder
Please touch the device.
AUR Explicit (1): pacfinder-1.2-1
:: (1/1) Downloaded PKGBUILD: pacfinder
  1 pacfinder                        (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 1
[...]
```

Like you suggested - a cleanBuild fixed the problem.
Thank you for your help & for creating PacFinder! :)
